{% set version = "3.8-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metafor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metafor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metafor/metafor_{{ version }}.tar.gz
  sha256: d694577f954144d8a5eeab6521fe1c87e68ddf9ecfd7ccc915d01533371b0514

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-mathjaxr
    - r-metadat
    - r-nlme
    - r-pbapply
  run:
    - r-base
    - r-matrix
    - r-mathjaxr
    - r-metadat
    - r-nlme
    - r-pbapply

test:
  commands:
    - $R -e "library('metafor')"           # [not win]
    - "\"%R%\" -e \"library('metafor')\""  # [win]

about:
  home: http://www.metafor-project.org https://github.com/wviechtb/metafor http://www.wvbauer.com
  license: GPL-2.0-or-later
  summary: A comprehensive collection of functions for conducting meta-analyses in R. The package includes functions to calculate various effect sizes or outcome measures, fit fixed-, random-, and mixed-effects models to such data, carry out moderator and meta-regression analyses, and create various types of meta-analytical
    plots (e.g., forest, funnel, radial, L'Abbe, Baujat, GOSH plots). For meta-analyses of binomial and person-time data, the package also provides functions that implement specialized methods, including the Mantel-Haenszel method, Peto's method, and a variety of suitable generalized linear (mixed-effects) models (i.e.,
    mixed-effects logistic and Poisson regression models). Finally, the package provides functionality for fitting meta-analytic multivariate/multilevel models that account for non-independent sampling errors and/or true effects (e.g., due to the inclusion of multiple treatment studies, multiple endpoints, or other forms
    of clustering). Network meta-analyses and meta-analyses accounting for known correlation structures (e.g., due to phylogenetic relatedness) can also be conducted.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: metafor
# Version: 2.1-0
# Date: 2019-05-13
# Title: Meta-Analysis Package for R
# Authors@R: person(given = "Wolfgang", family = "Viechtbauer", role = c("aut","cre"), email = "wvb@metafor-project.org", comment = c(ORCID = "0000-0003-3463-4063"))
# Depends: R (>= 3.5.0), methods, Matrix
# Imports: stats, utils, graphics, grDevices, nlme
# Suggests: lme4, numDeriv, minqa, nloptr, dfoptim, ucminf, CompQuadForm, mvtnorm, Formula, BiasedUrn, Epi, multcomp, gsl, sp, survival, boot, MASS, crayon, R.rsp, testthat, rmarkdown
# Description: A comprehensive collection of functions for conducting meta-analyses in R. The package includes functions to calculate various effect sizes or outcome measures, fit fixed-, random-, and mixed-effects models to such data, carry out moderator and meta-regression analyses, and create various types of meta-analytical plots (e.g., forest, funnel, radial, L'Abbe, Baujat, GOSH plots). For meta-analyses of binomial and person-time data, the package also provides functions that implement specialized methods, including the Mantel-Haenszel method, Peto's method, and a variety of suitable generalized linear (mixed-effects) models (i.e., mixed-effects logistic and Poisson regression models). Finally, the package provides functionality for fitting meta-analytic multivariate/multilevel models that account for non-independent sampling errors and/or true effects (e.g., due to the inclusion of multiple treatment studies, multiple endpoints, or other forms of clustering). Network meta-analyses and meta-analyses accounting for known correlation structures (e.g., due to phylogenetic relatedness) can also be conducted.
# License: GPL (>= 2)
# ByteCompile: TRUE
# LazyData: TRUE
# Encoding: UTF-8
# VignetteBuilder: R.rsp
# URL: http://www.metafor-project.org https://github.com/wviechtb/metafor http://www.wvbauer.com
# BugReports: https://github.com/wviechtb/metafor/issues
# NeedsCompilation: no
# Packaged: 2019-05-13 16:20:41 UTC; wviechtb
# Author: Wolfgang Viechtbauer [aut, cre] (<https://orcid.org/0000-0003-3463-4063>)
# Maintainer: Wolfgang Viechtbauer <wvb@metafor-project.org>
# Repository: CRAN
# Date/Publication: 2019-05-14 10:20:03 UTC
