{% set version = "4.6-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metafor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/metafor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/metafor/metafor_{{ version }}.tar.gz
  sha256: 07344cc3bd87b8bd25ef998e9a6ce322ae8e448ef5af06ec3e79631724e18666

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-mathjaxr
    - r-metadat
    - r-nlme
    - r-numderiv
    - r-pbapply
  run:
    - r-base
    - r-matrix
    - r-mathjaxr
    - r-metadat
    - r-nlme
    - r-numderiv
    - r-pbapply

test:
  commands:
    - $R -e "library('metafor')"           # [not win]
    - "\"%R%\" -e \"library('metafor')\""  # [win]

about:
  home: https://www.metafor-project.org https://www.wvbauer.com
  dev_url: https://github.com/wviechtb/metafor
  doc_url: https://wviechtb.github.io/metafor/
  license: GPL-2.0-or-later
  summary: A comprehensive collection of functions for conducting meta-analyses in R. The package includes functions to calculate various effect sizes or outcome measures, fit fixed-, random-, and mixed-effects models to such data, carry out moderator and meta-regression analyses, and create various types of meta-analytical
    plots (e.g., forest, funnel, radial, L'Abbe, Baujat, GOSH plots). For meta-analyses of binomial and person-time data, the package also provides functions that implement specialized methods, including the Mantel-Haenszel method, Peto's method, and a variety of suitable generalized linear (mixed-effects) models (i.e.,
    mixed-effects logistic and Poisson regression models). Finally, the package provides functionality for fitting meta-analytic multivariate/multilevel models that account for non-independent sampling errors and/or true effects (e.g., due to the inclusion of multiple treatment studies, multiple endpoints, or other forms
    of clustering). Network meta-analyses and meta-analyses accounting for known correlation structures (e.g., due to phylogenetic relatedness) can also be conducted.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
